language: r
r:
  - oldrel
  - release
  - devel

sudo: false
dist: trusty

cache: packages

os:
  - linux
  - osx

r_packages:
  - covr
  - testthat

r_github_packages:
  - jimhester/lintr

env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
    - LINTR_COMMENT_BOT=false

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'lintr::lint_package()'
