language: r

sudo: false

cache: packages

r_packages:
  - covr
  - testthat

r_github_packages:
  - jimhester/lintr

env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'lintr::lint_package()'
