language: r
r:
  - release
  - devel

sudo: required
dist: trusty

cache: packages

r_packages:
  - devtools
  - covr
  - testthat
  - lintr

before_install:
  - sudo apt-get install valgrind

env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
    - LINTR_COMMENT_BOT=false

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e "devtools::install_github('dirmeier/diffusr')"
  - R -d "valgrind --tool=memcheck --leak-check=full --track-origins=yes" --vanilla < diffusr.Rcheck/diffusr-Ex.R
